/**
 *  All constants should go here
 */
export const HEADER_DATA = 'HEADER_DATA';
export const HEADER_DATA_SUCCESS = 'HEADER_DATA_SUCCESS';
export const HEADER_DATA_ERROR = 'HEADER_DATA_ERROR';
export const LOAD_REPO_DATA = 'LOAD_REPO_DATA';
export const LOAD_REPO_DATA_SUCCESS = 'LOAD_REPO_DATA_SUCCESS';
export const LOAD_REPO_DATA_ERROR = 'LOAD_REPO_DATA_ERROR';
export const LOAD_LANGUAGES = 'LOAD_LANGUAGES';
export const LOAD_LANGUAGES_SUCCESS = 'LOAD_LANGUAGES_SUCCESS';
export const LOAD_LANGUAGES_ERROR = 'LOAD_LANGUAGES_ERROR';
export const LOAD_STARS = 'LOAD_STARS';
export const LOAD_STARS_SUCCESS = 'LOAD_STARS_SUCCESS';
export const LOAD_STARS_ERROR = 'LOAD_STARS_ERROR';
export const LOAD_FILTER_DATA = 'LOAD_FILTER_DATA';
export const LOAD_FILTER_DATA_SUCCESS = 'LOAD_FILTER_DATA_SUCCESS';
export const LOAD_FILTER_DATA_ERROR = 'LOAD_FILTER_DATA_ERROR';
export const REPO_SEARCH = 'REPO_SEARCH';
export const REPO_SEARCH_SUCCESS = 'REPO_SEARCH_SUCCESS';
export const REPO_SEARCH_ERROR = 'REPO_SEARCH_ERROR';
export const LAZY_LOADER_ACTIVATED = 'LAZY_LOADER_ACTIVATED';
export const LAZY_LOADER_ERROR = 'LAZY_LOADER_ERROR';
export const LAZY_LOADER_SUCCESS = 'LAZY_LOADER_SUCCESS';
